- name: Verify
  hosts: all
  tasks:
    - name: Get infos on EL container
      community.docker.docker_container_info:
        name: "{{ ethereum_node_el }}"
      register: ethereum_node_result_el
    - name: Get infos CL container
      community.docker.docker_container_info:
        name: "{{ ethereum_node_cl }}"
      register: ethereum_node_result_cl
    - name: Show infos
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - ethereum_node_result_el
        - ethereum_node_result_cl
    - name: Assert results
      ansible.builtin.assert:
        that:
          - "ethereum_node_result_el.container.State.Running == true"
          - "ethereum_node_result_cl.container.State.Running == true"
