- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart chaosd
  ansible.builtin.systemd:
    name: chaosd
    state: restarted

- name: Restart chaos-iptables-bridge
  ansible.builtin.systemd:
    name: chaos-iptables-bridge
    state: restarted

- name: Reload nginx-proxy
  community.docker.docker_container:
    name: "{{ docker_nginx_proxy_container_name | default('nginx-proxy') }}"
    restart: true
  failed_when: false
