- name: Verify
  hosts: all
  tasks:
    - name: Get infos on EL container
      community.docker.docker_container_info:
        name: "blockscout"
      register: blockscout_result
    - name: Show infos
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - blockscout_result
