- name: Verify
  hosts: all
  tasks:
    - name: Wait and let the container start
      ansible.builtin.pause:
        seconds: 5
    - name: Get infos from container
      community.docker.docker_container_info:
        name: "{{ mev_rs_container_name }}"
      register: mev_rs_result_container
    - name: Show infos
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - mev_rs_result_container
    - name: Assert results
      ansible.builtin.assert:
        that:
          - "mev_rs_result_container.container.State.Running == true"
