reth_user: reth
reth_datadir: /data/reth
reth_auth_jwt_path: /data/execution-auth.secret
reth_announced_ip: "{{ ansible_host }}"
reth_announced_ipv6: "{{ ansible_default_ipv6.address if reth_ipv6_enabled and ansible_default_ipv6.address is defined else '' }}"

reth_cleanup: false # when set to "true" it will remove the container

reth_ports_p2p: 30303
reth_ports_http_rpc: 8545
reth_ports_engine: 8551
reth_ports_metrics: 6060

reth_ipv6_enabled: false

reth_container_name: reth
reth_container_image: ghcr.io/paradigmxyz/reth
reth_container_env: {}
reth_container_ports_ipv4:
  - "127.0.0.1:{{ reth_ports_http_rpc }}:{{ reth_ports_http_rpc }}"
  - "127.0.0.1:{{ reth_ports_engine }}:{{ reth_ports_engine }}"
  - "0.0.0.0:{{ reth_ports_p2p }}:{{ reth_ports_p2p }}"
  - "0.0.0.0:{{ reth_ports_p2p }}:{{ reth_ports_p2p }}/udp"

reth_container_ports_ipv6:
  - "[::]:{{ reth_ports_p2p }}:{{ reth_ports_p2p }}"
  - "[::]:{{ reth_ports_p2p }}:{{ reth_ports_p2p }}/udp"

reth_container_ports: >-
  {{ reth_container_ports_ipv4 + (reth_container_ports_ipv6 if reth_ipv6_enabled and ansible_default_ipv6.address is defined else []) }}

reth_container_volumes:
  - "{{ reth_datadir }}:/data"
  - "{{ reth_auth_jwt_path }}:/execution-auth.jwt:ro"
reth_container_security_opts: []
reth_container_stop_timeout: "300"
reth_container_networks: []
reth_container_command_default:
  - node
  - --datadir=/data
  - --log.file.directory=/data/logs
  - --port={{ reth_ports_p2p }}
  - --http
  - --http.addr=0.0.0.0
  - --http.port={{ reth_ports_http_rpc }}
  - --authrpc.addr=0.0.0.0
  - --authrpc.port={{ reth_ports_engine }}
  - --authrpc.jwtsecret=/execution-auth.jwt
  - --nat=extip:{{ reth_announced_ip }}
  - --metrics=0.0.0.0:{{ reth_ports_metrics }}

reth_container_command_v6: []
  # - --nat=extip:{{ reth_announced_ipv6 }} # not supported

reth_container_command: >-
  {{ reth_container_command_default + (reth_container_command_v6 if reth_ipv6_enabled and ansible_default_ipv6.address is defined else []) }}

reth_container_command_extra_args: []
#  - --http.api=eth,net,web3
#  - --http.vhosts=*

# Default image pull policy
reth_container_pull: false


# rbuilder - https://github.com/flashbots/rbuilder
reth_rbuilder_enabled: false
reth_rbuilder_config_path: /data/rbuilder.toml
reth_rbuilder_container_volumes:
  - "{{ reth_rbuilder_config_path }}://rbuilder-config.toml:ro"
reth_rbuilder_container_args:
  - --rbuilder.config=/rbuilder-config.toml

reth_rbuilder_config: |
  log_json = true
  log_level = "info,rbuilder=debug"
  redacted_telemetry_server_port = 6061
  redacted_telemetry_server_ip = "0.0.0.0"
  full_telemetry_server_port = 6060
  full_telemetry_server_ip = "0.0.0.0"

  chain = "mainnet"
  reth_datadir = "/data"

  coinbase_secret_key = "env:COINBASE_SECRET_KEY"
  relay_secret_key = "env:RELAY_SECRET_KEY"
  optimistic_relay_secret_key = "env:OPTIMISTIC_RELAY_SECRET_KEY"

  # cl_node_url can be a single value, array of values, or passed by an environment variables with values separated with a comma
  # cl_node_url = "http://localhost:3500"
  cl_node_url = ["env:CL_NODE_URL"]
  jsonrpc_server_port = 8645
  jsonrpc_server_ip = "0.0.0.0"
  el_node_ipc_path = "/tmp/reth.ipc"
  extra_data = "âš¡ðŸ¤–"

  dry_run = true
  dry_run_validation_url = "http://localhost:8545"

  ignore_cancellable_orders = true

  # genesis_fork_version = "0x00112233"

  sbundle_mergeable_signers = []
  live_builders = ["mp-ordering", "mgp-ordering", "merging"]

  enabled_relays = ["flashbots"]

  [[builders]]
  name = "mgp-ordering"
  algo = "ordering-builder"
  discard_txs = true
  sorting = "mev-gas-price"
  failed_order_retries = 1
  drop_failed_orders = true

  [[builders]]
  name = "mp-ordering"
  algo = "ordering-builder"
  discard_txs = true
  sorting = "max-profit"
  failed_order_retries = 1
  drop_failed_orders = true

  [[builders]]
  name = "parallel"
  algo = "parallel-builder"
  discard_txs = true
  num_threads = 25
